const { EmbedBuilder } = require('discord.js');

exports.errorMessage = async (msg,title,description) =>{

    const errEmbed = new EmbedBuilder()
    .setColor('#0099ff')
    .setTitle(title)
    .setTimestamp()
    .setDescription(description)
    .setFooter({text: 'Generated by Kittr Bot'})
    .setThumbnail("https://cdn-icons-png.flaticon.com/512/148/148766.png")
       
    msg.channel.send({ embeds: [errEmbed] });
}